name: Heroku-Deployment

on:
  push:
    branches: main

  workflow_dispatch:

jobs:
   
  deploy:
    runs-on: windows-latest
    
    strategy:
      max-parallel: 1
    
    steps:
      - uses: actions/checkout@v3

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "appy-test"
          heroku_email: ${{secrets.EMAIL}}
          branch: "main"
